let Temp=[                {   
    courseTitle:"HTML",
    "courseTopics":[
        {   "topicNo":1,
            "topic":"Elements",
            "isCompleted":true,
            "url":"https://www.youtube.com",
            gitLink:"https://github.com"
        },
        {
            "topicNo":2,
            "topic":"Atrrtibutes",
            "isCompleted":false,
            "url":"",
            "gitLink":"https://github.com"

        },
        {
            "topicNo":3,
            "topic":"Content",
            "isCompleted":true,
            "url":"https://www.youtube.com",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":4,
            "topic":"Comments",
            "isCompleted":false,
            "url":"",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":5,
            "topic":"Heading",
            "isCompleted":true,
            "url":"https://www.youtube.com",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":6,
            "topic":"Paragraph",
            "isCompleted":false,
            "url":"",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":7,
            "topic":"Formating",
            "isCompleted":true,
            "url":"https://www.youtube.com",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":8,
            "topic":"Block&Inline",
            "isCompleted":true,
            "url":"https://www.youtube.com",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":9,
            "topic":"Link",
            "isCompleted":false,
            "url":"",
            "gitLink":"https://github.com"
        },
        {
            "topicNo":10,
            "topic":"Tables",
            "isCompleted":true,
            "url":"https://www.youtube.com"
        }
    ]
},]
export default Temp;
