const PacData=[
    {
        "id":20,
        "batch":"FED09",
        "courseData":
            [
                {   
                    "courseTitle":"HTML",
                    "courseTopics":[
                        {   "topicNo":1,
                            "topic":"Elements",
                            "gitLink":null
                        },
                        {
                            "topicNo":2,
                            "topic":"Atrrtibutes",
                            "gitLink":null

                        },
                        {
                            "topicNo":3,
                            "topic":"Content",
                            "gitLink":null
                        },
                        {
                            "topicNo":4,
                            "topic":"Comments",
                            "gitLink":null
                        },
                        {
                            "topicNo":5,
                            "topic":"Heading",
                            "gitLink":null
                        },
                        {
                            "topicNo":6,
                            "topic":"Paragraph",
                            "gitLink":null
                        },
                        {
                            "topicNo":7,
                            "topic":"Formating",
                            "gitLink":null
                        },
                        {
                            "topicNo":8,
                            "topic":"Block&Inline",
                            "gitLink":null
                        },
                        {
                            "topicNo":9,
                            "topic":"Link",
                            "gitLink":null
                        },
                        {
                            "topicNo":10,
                            "topic":"Tables",
                            "gitLink":null
                        }
                    ]
            },
            {
                "courseTitle":"CSS",
                "courseTopics":[
                    {
                        "topicNo":1,
                        "topic":"Introduction",
                        "gitLink":null
                    },
                    {
                        "topicNo":2,
                        "topic":"Syntax",
                        "gitLink":null
                    },
                    {
                        "topicNo":3,
                        "topic":"Selectors",
                        "gitLink":null
                    },
                    {
                        "topicNo":4,
                        "topic":"Units",
                        "gitLink":null
                    },
                    {
                        "topicNo":5,
                        "topic":"Comments",
                        "gitLink":null
                    },
                    {
                        "topicNo":6,
                        "topic":"Types",
                        "gitLink":null
                    },
                    {
                        "topicNo":7,
                        "topic":"Text",
                        "gitLink":null
                    },
                    {
                        "topicNo":8,
                        "topic":"Fonts",
                        "gitLink":null
                    },
                    {
                        "topicNo":9,
                        "topic":"Colors",
                        "gitLink":null
                    },
                    {
                        "topicNo":10,
                        "topic":"Specificity",
                        "gitLink":null
                    }
                ]
            },
            {
                "courseTitle":"JS",
                "courseTopics":[
                    {
                        "topicNo":1,
                        "topic":"Introduction",
                        "gitLink":null
                    },
                    {
                        "topicNo":2,
                        "topic":"Data Types",
                        "gitLink":null
                    },
                    {
                        "topicNo":3,
                        "topic":"Variable",
                        "gitLink":null
                    },
                    {
                        "topicNo":4,
                        "topic":"Storage",
                        "gitLink":null
                    },
                    {
                        "topicNo":5,
                        "topic":"Operators",
                        "gitLink":null
                    },
                    {
                        "topicNo":6,
                        "topic":"Expressions",
                        "gitLink":null
                    },
                    {
                        "topicNo":7,
                        "topic":"Conditions",
                        "gitLink":null
                    },
                    {
                        "topicNo":8,
                        "topic":"Loops",
                        "gitLink":null
                    },
                    {
                        "topicNo":9,
                        "topic":"Scope",
                        "gitLink":null
                    },
                    {
                        "topicNo":10,
                        "topic":"Functions",
                        "gitLink":null
                    }
                ]
            },
            {
                "courseTitle":"React-JS",
                "courseTopics":[
                    {
                        "topicNo":1,
                        "topic":"Introduction",
                        "gitLink":null
                    },
                    {
                        "topicNo":2,
                        "topic":"Create-React-App",
                        "gitLink":null
                    },
                    {
                        "topicNo":3,
                        "topic":"React-JSX",
                        "gitLink":null
                    },
                    {
                        "topicNo":4,
                        "topic":"React-Components",
                        "gitLink":null
                    },
                    {
                        "topicNo":5,
                        "topic":"Functional-Components",
                        "gitLink":null
                    },
                    {
                        "topicNo":6,
                        "topic":"Class-Components",
                        "gitLink":null
                    },
                    {
                        "topicNo":7,
                        "topic":"React-Props",
                        "gitLink":null
                    },
                    {
                        "topicNo":8,
                        "topic":"React-State",
                        "gitLink":null
                    },
                    {
                        "topicNo":9,
                        "topic":"React-Lists",
                        "gitLink":null
                    },
                    {
                        "topicNo":10,
                        "topic":"React-Lifecycle",
                        "gitLink":null
                    }
                ]
            }
        ]
        
        
    },
    {
        "id":21,
        "batch":"FED10",
        "courseData":[
            {   
                "courseTitle":"Angular",
                "courseTopics":[
                    {
                        "topicNo":1,
                        "topic":"Modules",
                        "gitLink":null
                    },
                    {
                        "topicNo":2,
                        "topic":"Directives",
                        "gitLink":null
                    },
                    {
                        "topicNo":3,
                        "topic":"Data-Binding",
                        "gitLink":null
                    },
                    {
                        "topicNo":4,
                        "topic":"Controllers",
                        "gitLink":null
                    },
                    {
                        "topicNo":5,
                        "topic":"Scopes",
                        "gitLink":null
                    },
                    {
                        "topicNo":6,
                        "topic":"Filters",
                        "gitLink":null
                    },
                    {
                        "topicNo":7,
                        "topic":"Http",
                        "gitLink":null
                    },
                    {
                        "topicNo":8,
                        "topic":"Sql",
                        "gitLink":null
                    },
                    {
                        "topicNo":9,
                        "topic":"Select",
                        "gitLink":null
                    },
                    {
                        "topicNo":10,
                        "topic":"Events",
                        "gitLink":null
                    }
                ]
        },
        {
            "courseTitle":"NodeJS",
            "courseTopics":[
                {
                    "topicNo":1,
                    "topic":"File-System",
                    "gitLink":null
                },
                {
                    "topicNo":2,
                    "topic":"URL-Module",
                    "gitLink":null
                },
                {
                    "topicNo":3,
                    "topic":"Npm",
                    "gitLink":null
                },
                {
                    "topicNo":4,
                    "topic":"Uplod-Files",
                    "gitLink":null
                },
                {
                    "topicNo":5,
                    "topic":"Node-Email",
                    "gitLink":null
                },
                {
                    "topicNo":6,
                    "topic":"Node-Types",
                    "gitLink":null
                },
                {
                    "topicNo":7,
                    "topic":"Node-Fuction",
                    "gitLink":null
                },
                {
                    "topicNo":8,
                    "topic":"Data-structure",
                    "gitLink":null
                },
                {
                    "topicNo":9,
                    "topic":"Handle-Node",
                    "gitLink":null
                },
                {
                    "topicNo":10,
                    "topic":"Node-verison",
                    "gitLink":null
                }
            ]
        },
        {
            "courseTitle":"MongoDB",
            "courseTopics":[
                {
                    "topicNo":1,
                    "topic":"Crete-Data",
                    "gitLink":null
                },
                {
                    "topicNo":2,
                    "topic":"Insert",
                    "gitLink":null
                },
                {
                    "topicNo":3,
                    "topic":"Find",
                    "gitLink":null
                },
                {
                    "topicNo":4,
                    "topic":"Query",
                    "gitLink":null
                },
                {
                    "topicNo":5,
                    "topic":"Sort",
                    "gitLink":null
                },
                {
                    "topicNo":6,
                    "topic":"Delete",
                    "gitLink":null
                },
                {
                    "topicNo":7,
                    "topic":"Drop-Collection",
                    "gitLink":null
                },
                {
                    "topicNo":8,
                    "topic":"Update",
                    "gitLink":null
                },
                {
                    "topicNo":9,
                    "topic":"Limit",
                    "gitLink":null
                },
                {
                    "topicNo":10,
                    "topic":"Join",
                    "gitLink":null
                }
            ]
        },
        {
            "courseTitle":"Phython",
            "courseTopics":[
                {
                    "topicNo":1,
                    "topic":"Data-Types",
                    "gitLink":null
                },
                {
                    "topicNo":2,
                    "topic":"Conversion",
                    "gitLink":null
                },
                {
                    "topicNo":3,
                    "topic":"NameSpace",
                    "gitLink":null
                },
                {
                    "topicNo":4,
                    "topic":"Phython-Pass",
                    "gitLink":null
                },
                {
                    "topicNo":5,
                    "topic":"Modules",
                    "gitLink":null
                },
                {
                    "topicNo":6,
                    "topic":"Package",
                    "gitLink":null
                },
                {
                    "topicNo":7,
                    "topic":"Dictionary",
                    "gitLink":null
                },
                {
                    "topicNo":8,
                    "topic":"Directory",
                    "gitLink":null
                },
                {
                    "topicNo":9,
                    "topic":"Exception",
                    "gitLink":null
                },
                {
                    "topicNo":10,
                    "topic":"OPP",
                    "gitLink":null
                }
            ]
        }
    ]
    
    }
]
export default PacData;